<a href="https://colab.research.google.com/github/Ajayrao29/Machine_Learning_Course/blob/main/01_NumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Numpy - Numerical Python



Advantages of NumPy Arrays :

1. Allows several Mathematical Operations.
2. Faster Operations.


 NumPy Documentation :  https://numpy.org/doc/ (refer this to learn more about NumPy)

In [19]:
#importing numpy library
import numpy as np

#List vs NumPy - Time Taken

In [2]:
from time import process_time
 #time is someother library from where we are importing process time.

  Time taken by list

In [7]:
#Example for evaluating the time taken by list
list1 = [i for i in range(10000)] # creating a list

start_time = process_time() # getting the start time

list2 = [i+5 for i in list1] # in between, iterating through the list1 and adding 5 to each element

end_time = process_time() # getting the end time

print(end_time - start_time) #calcualting time taken

0.0011198399999976516


Time taken by NumPy array

In [11]:
np_array = np.array([i for i in range(10000)])

start_time = process_time()

np_array += 5  # np_array = np_array + 5

end_time = process_time()

print(end_time - start_time)

0.0005485560000018097


So, we can say that NumPy operations are faster

#NumPy Arrays

In [12]:
#list
list1 = [1,2,3,4,5]
print(list1)
type(list1)

[1, 2, 3, 4, 5]


list

In [13]:
np_array = np.array([1,2,3,4,5])
print(np_array)
type(np_array)

[1 2 3 4 5]


numpy.ndarray

we find no commas in between the elements in NumPy array and the datatype is numpy.ndarray

#Creating Dimensional arrays and manipulations on them :

In [14]:
#creating 1-d array
a=np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [15]:
a.shape #gives you dimesions (it returns (4,) since it has 4 columns and 1-d)

(4,)

In [16]:
#creating 2-d array
b = np.array([(1,2,3,4),(5,6,7,8)])
print(b)
b.shape #gives you dimesions (it returns (2,4) since it has 2 rows and 4 columns)

[[1 2 3 4]
 [5 6 7 8]]


(2, 4)

In [17]:
c=np.array([(1,2,3,4),(5,6,7,8)],dtype=float) # dtype represents floating point here
print(c)                                      # default datatype is Integers

[[1. 2. 3. 4.]
 [5. 6. 7. 8.]]


#Creating NumPy arrays with initial placeholders

In [21]:
#Creating a numpy array of zeroes
np_array = np.zeros((4,5)) # 4 is no.of rows and 5 is no.of columns that we specify
print(np_array)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [22]:
#Creating a numpy arrays of ones
np_array = np.ones((4,5))
print(np_array)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


This np.zeros and np.ones is for 0's and 1's but for a particular value we can create like here under -

In [24]:
#Creating array of a particular value
np_array = np.full((4,5),5) #4 is no.of.rows and 5 is no.of.columns in (4,5) and 5 is value
print(np_array)

[[5 5 5 5 5]
 [5 5 5 5 5]
 [5 5 5 5 5]
 [5 5 5 5 5]]


In [25]:
#Creating an identity matrix
a = np.eye(5) #5 is the dimension where both no.of rows and columns are equal to 5
print(a)      # we use eye

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [26]:
#Creating NumPy array with random values
b=np.random.random((4,5))
print(b)  # all the values will be between 0 to 1 range

[[0.35111419 0.35646209 0.74252055 0.46064853 0.30004317]
 [0.27083    0.20207295 0.63260564 0.38388262 0.5495525 ]
 [0.3358334  0.17374643 0.13362812 0.78465533 0.3108276 ]
 [0.42259902 0.12166444 0.51507503 0.13141161 0.85659735]]


In [28]:
#Creating a NumPy array with random values (Specific range)
c = np.random.randint(10,100,(3,5)) #10,100 is range and 4,5 is dimensions
print(c)

[[72 10 16 82 29]
 [91 91 26 79 44]
 [72 73 22 49 33]]


In [29]:
# Creating a NumPy array with evenly space values (specifying no.of values needed)
d = np.linspace(10,30,6) #10,30 is range and 6 is no.of values we want between that range
print(d)

[10. 14. 18. 22. 26. 30.]


In [30]:
# Creating a NumPy array with evenly space values (specifying the step)
e = np.arange(10,30,5) #10,30 is range and 5 is step (each time add up by 5 and return in 10,30 range)
print(e)

[10 15 20 25]


In [31]:
# Convert a list to a NumPy array
list2 = [10,20,20,20,50]

np_array = np.asarray(list2)
print(np_array)
type(np_array) #returns numpy.ndarray (type of array)

[10 20 20 20 50]


numpy.ndarray

#Analysing a NumPy array

In [32]:
c = np.random.randint(10,90,(5,5)) # Here 10,50 is range and 5,5 is the dimensions
print(c)

[[67 89 76 27 53]
 [25 88 43 26 84]
 [45 49 84 35 82]
 [34 45 23 42 66]
 [69 79 39 53 87]]


In [33]:
# array dimension
print(c.ndim) # ndim gives the dimension of array

2


In [34]:
# No.of elements in the array
print(c.size)

25


In [35]:
# Checking the data type of elements in the array
print(c.dtype) # returns (int64) 64 bit integers values

int64


#Mathematical Operations on NumPy array

In [36]:
list1 = [1,2,3,4,5]
list2 = [6,7,8,9,10]
print(list1 + list2) # Concatenate or joins two list and not addition

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


In [37]:
a = np.random.randint(0,10,(3,3))
b = np.random.randint(10,20,(3,3))
print(a)
print(b)

[[1 2 0]
 [5 1 7]
 [3 2 2]]
[[11 10 16]
 [15 10 18]
 [12 15 15]]


In [38]:
print(a+b) # Addition
print(a-b) # Subtraction
print(a*b) # Multiplication
print(a/b) # Division

[[12 12 16]
 [20 11 25]
 [15 17 17]]
[[-10  -8 -16]
 [-10  -9 -11]
 [ -9 -13 -13]]
[[ 11  20   0]
 [ 75  10 126]
 [ 36  30  30]]
[[0.09090909 0.2        0.        ]
 [0.33333333 0.1        0.38888889]
 [0.25       0.13333333 0.13333333]]


or you can also do this way -->

In [39]:
print(np.add(a,b))
print(np.subtract(a,b))
print(np.multiply(a,b))
print(np.divide(a,b))

[[12 12 16]
 [20 11 25]
 [15 17 17]]
[[-10  -8 -16]
 [-10  -9 -11]
 [ -9 -13 -13]]
[[ 11  20   0]
 [ 75  10 126]
 [ 36  30  30]]
[[0.09090909 0.2        0.        ]
 [0.33333333 0.1        0.38888889]
 [0.25       0.13333333 0.13333333]]


#Array Manipulation

In [43]:
arr = np.random.randint(0,10,(2,3))
print(arr)
print(arr.shape)

[[9 7 4]
 [4 2 5]]
(2, 3)


In [44]:
#transpose
trans=np.transpose(arr)
print(trans)
print(trans.shape)

[[9 4]
 [7 2]
 [4 5]]
(3, 2)


or you can do this way -->

In [45]:
trans2 = arr.T
print(trans2)
print(trans2.shape)

[[9 4]
 [7 2]
 [4 5]]
(3, 2)


In [46]:
# Reshaping a array
a = np.random.randint(0,10,(2,3))
print(a)
print(a.shape)

[[7 4 7]
 [7 7 6]]
(2, 3)


In [47]:
#Reshaping above array
b = a.reshape(3,2)
print(b)
print(b.shape)

[[7 4]
 [7 7]
 [7 6]]
(3, 2)
